apps/cms/urls.py
from django.urls import path
from . import views,staff_views



app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('banners/', views.banners, name='banners'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('upload_file/', views.upload_file, name='upload_file'),


]

#员工管理
urlpatterns += [
    path('staffs',staff_views.staffs_view,name='staffs'),
    path('add_staff/',staff_views.AddStaffView.as_view(),name='add_staff'),
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('cache/', views.cache_test, name='cache'),
    path('register/', views.register, name='register'),

]

xfz/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('news/', include("apps.news.urls")),
    path('cms/', include('apps.cms.urls')),
    path('search/', views.search, name='search'),
    path('course/',include('apps.course.urls')),
    path('payinfo/',include('apps.payinfo.urls')),
    path('account/',include('apps.xfzauth.urls')),
    path('ueditor/',include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__', include(debug_toolbar.urls)))

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_681895_q7ptjm0r8n.css">
    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo-box">
                <a href="#"></a>
            </div>

            <ul class="nav">
                <li class="active"><a href="/">吃</a></li>
                <li><a href="#">喝</a></li>
                <li><a href="#">玩</a></li>
                <li><a href="#">乐</a></li>
            </ul>

            <div class="auth-box">
                <i class="icon-person iconfont"></i>
                {% if user.is_authenticated %}
                    <a href="#" class="authenticated-box">{{ user.username }}</a>
                    <div class="user-more-box">
                        <i class="triangle"></i>
                        {% if user.is_staff %}
                            <a href="{% url 'cms:index' %}">管理系统</a>
                        {% endif %}
                        <a href="{% url 'xfzauth:logout' %}">退出登录</a>
                    </div>
                {% else %}
                    <a href="#" class="signin-btn">登录</a> /
                    <a href="#" class="signup-btn">注册</a>
                {% endif %}
            </div>
        </div>
    </header>
    {% block main %}{% endblock %}
    <footer class="footer">
        <div class="top-group">
            <div class="top-inner-group">
                <div class="logo-box"></div>
                <div class="detail-group">
                    <div class="line1">
                        <ul class="links">
                            <li><a href="#">衣</a></li>
                            <li><a href="#">食</a></li>
                            <li><a href="#">住</a></li>
                            <li><a href="#">行</a></li>
                        </ul>
                        <div class="about-us">
                            <span class="title">关于我们：</span>
                            <ul class="social-group">
{#                                <li class="weixin">#}
{#                                    <div class="wx-qrcode"></div>#}
{#                                    <span class="text">6666666666#}
{#                                    </span>#}
{#                                </li>#}
                                <li class="weibo">
                                    <a class="text" href="#">小饭桌</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="line2">
                        <p class="address"></p>
                        <p class="contact"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-group">
        </div>
    </footer>
<div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-wrapper">
                    <div class="signin-group auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                            </div>
                             <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
{#                                <label class="remember-label">#}
{#                                    <input type="checkbox" name="remember" value="1">#}
{#                                    记住我#}
{#                                </label>#}
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即登录">
                            </div>
                        </div>
                    </div>
                    <div class="signup-group auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="{% url 'xfzauth:img_captcha' %}" alt="" class="img-captcha" style="cursor:pointer;">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password2" placeholder="确认密码">
                            </div>
{#                            <div class="input-group">#}
{#                                <div class="short-input-group">#}
{#                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">#}
{#                                </div>#}
{#                                <div class="input-group-addon">#}
{#                                    <span class="sms-captcha-btn">发送验证码</span>#}
{#                                </div>#}
{#                            </div>#}
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即注册">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>